# Examples
example_deps = [enki_dep]

executable('overlay_logo_demo',
  'overlay_logo_demo.cpp',
  dependencies : example_deps,
  install : false,
)

executable('clipboard_dnd_demo',
  'clipboard_dnd_demo.cpp',
  dependencies : example_deps,
  install : false,
)

executable('toplevel_dock_demo',
  'toplevel_dock_demo.cpp',
  dependencies : example_deps,
  install : false,
)

executable('outputs_monitor_demo',
  'outputs_monitor_demo.cpp',
  dependencies : example_deps,
  install : false,
)

executable('desktop_shell_demo',
  'desktop_shell_demo.cpp',
  dependencies : example_deps,
  install : false,
)

